const DEG = Math.PI / 180;

export const GameConfig = {
  logicalWidth: 1600,
  logicalHeight: 900,
  pixelsPerMeter: 6,
  groundScreenY: 780,
  worldAnchorScreenX: 300,
  // One third in from the left edge, leaving most of the view ahead (right).
  followScreenX: 540,
  fixedStep: 1 / 120,
  maxFrameDelta: 0.05,

  initialFallGravity: 38,
  gravity: 38,
  launchSpeed: 150,
  launchAngleMin: 15 * DEG,
  launchAngleMax: 75 * DEG,
  groundFriction: 36,
  stopSpeed: 1.5,

  player: {
    width: 5.5,
    height: 8,
    startX: 0,
    startY: -100,
  },

  hitter: {
    x: -7.5,
    width: 6,
    height: 16,
  },

  swing: {
    duration: 0.4,
    frameCount: 8,
    followThroughStart: 0.2,
    thickness: 1.2,
    launchWindowTopY: -28,
    launchWindowBottomY: -9,
    impactFlashDuration: 0.14,
    impactFlashRadius: 30.8,
  },

  slingshot: {
    forkWorldX: 23.333,
    frameSize: 220,
    frameTopSliceRatio: 0.52,
    backTipWorld: { x: 27.7, y: -28.35 },
    frontTipWorld: { x: 19.08, y: -28.35 },
    restPouchWorld: { x: 3.6, y: -25.4 },
    seatedOffset: { x: 30.5, y: -14.4 },
    seatedSize: 97,
    pouchWidth: 54,
    pouchHeight: 29,
    hotspotRadius: 108,
    maximumPull: 150,
    minimumPull: 36,
    minimumSpeed: 70,
    maximumSpeed: 180,
    minimumAngle: -80 * DEG,
    maximumAngle: 80 * DEG,
    cancelReturnDuration: 0.18,
    recoilOvershootDuration: 0.14,
    recoilDuration: 0.4,
    maximumSeatedTilt: 8 * DEG,
    limitPulseDuration: 0.12,
  },

  humanCannon: {
    wheelWorld: { x: 0, y: -5.7 },
    muzzleWorld: { x: 13.35, y: -16.42 },
    fuseWorld: { x: -8.2, y: -12.3 },
    powerBarWorld: { x: 4.62, y: -27.18 },
    loadedAnchor: { x: 558, y: 776 },
    emptyAnchor: { x: 500, y: 560 },
    spriteScale: 0.123,
    powerBarWidth: 160,
    powerBarHeight: 20,
    sweepDuration: 0.4,
    minimumSpeed: 50,
    maximumSpeed: 220,
    launchAngle: 26 * DEG,
    recoilDuration: 0.45,
    recoilDistance: 5,
    smokeDuration: 0.65,
  },

  missileTruck: {
    groundWorld: { x: 0, y: 0 },
    emptyAnchor: { x: 200, y: 620 },
    emptyScale: 0.25,
    loadedAnchor: { x: 319, y: 973 },
    loadedScale: 0.15867,
    loadedWorld: { x: 5.25, y: -20.4 },
    launchWorld: { x: 5.25, y: -20.4 },
    rackAngle: 26 * DEG,
    launchSpeed: 260,
    launchAngle: 22 * DEG,
  },

  skip: {
    approachWindow: 0.5,
    preImpactWindow: 0.1,
    postImpactWindow: 0.12,
    horizontalRetention: 0.88,
    verticalRetention: 0.6,
    minImpactSpeed: 150 * 0.3,
  },

  mine: {
    safeDistance: 150,
    firstMin: 420,
    firstMax: 650,
    intervalMin: 250,
    intervalMax: 900,
    signClearance: 12,
    width: 7,
    height: 2.8,
    horizontalMultiplier: 1.1,
    minimumHorizontalBoost: 120,
    verticalBoost: 90,
    generationAhead: 1100,
  },

  pickup: {
    safeDistance: 150,
    firstMaxDistance: 250,
    intervalMin: 100,
    intervalMax: 190,
    generationAhead: 1100,
    cleanupBehind: 320,
    radius: 20,
    magnetSpeed: 500,
    magnetCollectDistance: 2,
    // 未拾取道具的上下漂浮动效（屏幕像素与频率）。
    floatAmplitude: 7,
    floatFrequency: 0.6,
    redPacket: {
      weight: 0.5,
      minAltitude: 20,
      maxAltitude: 110,
      width: 8,
      height: 6,
    },
    skyLantern: {
      weight: 0.18,
      minAltitude: 20,
      maxAltitude: 110,
      width: 7,
      height: 10,
    },
    sixthGenJet: {
      weight: 0.18,
      minAltitude: 40,
      maxAltitude: 120,
      width: 18,
      height: 7,
    },
    ufo: {
      weight: 0.14,
      minAltitude: 65,
      maxAltitude: 120,
      width: 11,
      height: 7,
    },
  },

  powerUp: {
    lantern: {
      ascentDistance: 90,
      ascentSpeed: 30,
    },
    jet: {
      duration: 3.5,
      speed: 150,
      exitSpeed: 120,
      trailExhaustOffsetX: 43,
      trailEngineOffsetY: 4.5,
      trailWidth: 6,
      trailPuffSpacing: 7,
      trailPuffRadius: 5.5,
    },
    ufo: {
      duration: 5,
      speed: 120,
      exitSpeed: 120,
      displayWidth: 25,
      displayHeight: 50 / 3,
      lightBlinkInterval: 0.18,
      emitterOffsetY: 5.5,
      beamTopWidth: 5.5,
      beamSpreadAngle: Math.PI / 18,
      beamTopCapHeight: 1.1,
      beamGroundCapHeight: 2.1,
    },
  },

  signs: {
    interval: 200,
  },

  camera: {
    followRate: 6,
    verticalFollowRate: 6,
    verticalFollowScreenY: 260,
    shakeDuration: 0.28,
    shakeStrength: 10,
  },

  palette: {
    sky: "#bde9ff",
    skyDeep: "#8ed8f5",
    sun: "#ffd45c",
    cloud: "#fffdf5",
    ground: "#f1d39b",
    groundTop: "#3e9b65",
    groundDark: "#ca9b5d",
    ink: "#142033",
    player: "#eb4d4b",
    playerEdge: "#a92e35",
    hitter: "#2869d8",
    hitterEdge: "#17499b",
    club: "#142033",
    clubHead: "#fffdf5",
    sign: "#fffdf5",
    mine: "#d92f39",
    mineDark: "#7f1d2d",
    explosion: "#ff9f1c",
    explosionLight: "#ffe04a",
    redPacket: "#ef3340",
    redPacketDark: "#b91c2b",
    gold: "#ffc83d",
    lanternOrange: "#ff5a1f",
    lanternYellow: "#ffd166",
    jet: "#4b5563",
    jetLight: "#94a3b8",
    jetAccent: "#e3343f",
    ufo: "#d6d7df",
    ufoDark: "#8f96a8",
    ufoLight: "#18d8d3",
    ufoScreen: "#ffdc63",
  },
} as const;
